name: CMake

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: DiscordRPC-Submodule
      run: git submodule update --init
      
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        ref: x86-64-support-sourcesdk
        path: 'garrysmod_common'
     
    - name: Install Premake
      run: |
         curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-windows.zip -o premake.zip
         tar -xf premake.zip
         
    - name: Build DRPC
      run: |
          cmake discord-rpc\ -A Win32 -DUSE_STATIC_CRT=ON -B "ds_build32"
          cmake discord-rpc\  -DUSE_STATIC_CRT=ON -B "ds_build64"
          cmake --build ds_build32 --config Release
          cmake --build ds_build64 --config Release
          
    - name: Generate Project
      run: ./premake5.exe --gmcommon=garrysmod_common vs2019
      
    - name: Build 32
      run: |
        cd projects/windows/vs2019
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release /p:Platform=Win32 carefree_project_rpc.sln
    
    - uses: actions/upload-artifact@v3
      with:
        name: gmsv_eightbit_windows.dll
        path: projects/windows/vs2019/x86/Release/gmcl_carefree_project_rpc_win32.dll
    
    - name: Build 64
      run: |
        cd projects/windows/vs2019
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release /p:Platform=x64 carefree_project_rpc.sln
    
    - uses: actions/upload-artifact@v3
      with:
        name: gmsv_eightbit_win64.dll
        path: projects/windows/vs2019/x86_64/Release/gmcl_carefree_project_rpc_win64.dll
